[package]
name = "trusty-epub"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
log.workspace = true
quick-xml = "0.38.0"
thiserror = "2.0.12"
zip = { version = "0.6.6", default-features = true, features = ["deflate"] }

[lib]
path = "src/lib.rs"
